name = "TComp"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["TComp"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
weak.linter.style.header = false # el formato de copyright de Mathlib no aplica a este proyecto
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.35.0-rc4"

[[lean_lib]]
name = "TComp"
